# Generated by Django 3.2.20 on 2023-08-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='createad_timestamp',
            new_name='created_timestamp',
        ),
    ]
